image: python:3.13

stages:
  - build
  - deploy_ec2

build:
  stage: build
  script:
    - echo "Building the application..."
    - pip install -r requirements.txt  # Install dependencies

deploy_ec2:
  stage: deploy_ec2
  before_script:
    - mkdir -p ~/.ssh
    - echo "$AWS_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $AWS_PUBLIC_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying application to EC2"
    - |
      ssh -o StrictHostKeyChecking=no $AWS_USERNAME@$AWS_PUBLIC_IP << 'EOF'
        set -e
        sudo yum update -y
        sudo su
        cd /var/lib/pgsql/data/
        sudo rm -rf /var/lib/pgsql/data/*
        sudo yum install postgresql15-server -y
        sudo systemctl enable postgresql
        
        # Initialize the PostgreSQL database with the correct syntax
        echo "Initializing PostgreSQL database..."
        sudo -u postgres postgresql-setup --initdb --unit postgresql
        sudo systemctl start postgresql

        echo "Cloning application repository..."
        cd ~ 
        cd /home/ec2-user/nodeplay
        sudo yum install git
        git clone https://github.com/mdanialn/Ec2Deploy.git
        cd Ec2Deploy
        python3 -m venv venv
        source venv/bin/activate
        sudo chown -R ec2-user:ec2-user /home/ec2-user/nodeplay/Ec2Deploy/venv
        pip install --upgrade pip
        pip install -r requirements.txt

        # Setting up environment variables for database connection
        echo "Setting up environment variables..."
        export DB_HOST="$DB_HOST"
        export DB_USER="$DB_USER"
        export DB_PASSWORD="$DB_PASSWORD"
        
        echo $DB_HOST
        echo $DB_USER
        echo $DB_PASSWORD

        echo "Starting the application..."
        nohup python app.py &
        APP_PID=$!
        echo "Application started with PID: $APP_PID"

        # Wait for 5 minutes
        echo "Application will run for 5 minutes..."
        sleep 300

        # Terminate the application
        echo "Terminating the application..."
        kill $APP_PID || echo "Application already terminated"
        
      EOF
      # Add a newline character here to properly terminate the here document
  only:
    - main
