image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: us-east-1  # Change to your region
  EC2_INSTANCE: your-ec2-instance-ip  # Replace with your EC2 instance IP
  DOCKER_IMAGE: your-docker-image-name  # Replace with your Docker image name

before_script:
  - apk add --no-cache py-pip
  - pip install awscli

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  script:
    - |
      ssh -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE << 'EOF'
      docker pull $DOCKER_IMAGE:latest
      docker stop myapp || true
      docker rm myapp || true
      docker run -d --name myapp -p 80:80 $DOCKER_IMAGE:latest
      EOF
